name: Python Playwright Tests

on:
  push:
    branches:
      - main
      - dev
      - feature**
  pull_request:
    branches:
      - main
      - dev
      - feature**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # or 3.12/3.13 depending on your project

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # Run pytest unit tests
      - name: Run unit tests with pytest
        run: |
          pytest tests/e2e --html=reports/unit/report.html --self-contained-html -v

      # Run pytest E2E tesst
      - name: Run E2E tests with pytest
        run: |
          pytest tests/e2e --html=reports/e2e/report.html --self-contained-html -v

      # Upload HTML unit test report as GitHub artifact
      - name: Upload unit test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/unit/report.html

      # Upload HTML E2E test report as GitHub artifact
      - name: Upload E2E test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/e2e/report.html
